version: 2

jobs:
  test:
    docker:
      - image: node:8.15.1-stretch

    working_directory: ~/hetmech-frontend

    steps:
      - checkout
      - run:
          name: Frontend tests
          command: |
            npm install
            npm test
            npm build

  deploy:
    docker:
      - image: node:8.15.1-stretch
    steps:
      - checkout
      - attach_workspace:
          at: build
      - run:
          name: Install and configure dependencies
          command: |
            npm install --global --silent gh-pages@2.0.1
            git config user.email "ci-build@circleci.com"
            git config user.name "CircleCI Deploy Job"
      - run:
          name: Deploy build to gh-pages branch
          command: gh-pages --dist build

workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
